run:
  deadline: 5m

linters:
  enable:
    - errcheck
    - goimports
    - govet
    - goconst
    - gocyclo
    - gofmt
    - revive
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - wrapcheck
  disable:
    - gosimple
    - staticcheck
    - structcheck
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/oidc-soma/aerosquirrel
  gosec:
    excludes:
      - G107  # Potential HTTP request made with variable url

issues:
  exclude-use-default: false
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - text: "G112:"
      linters:
        - gosec
