name: Go Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/go-base-docker-publish.yaml
    secrets: inherit
    with:
      go_version: "1.19"
      package_path: "./"
      dockerfile_path: "."
      docker_username: "wlghks0314"
      image_repository: "aerosquirrel"
      image_tag: "latest"
