# Prerequisite: Create a secret named DOCKER_PASSWORD with your Docker Hub password
name: Go Base Docker Publish Reusable Workflow

on:
  workflow_call:
    inputs:
      go_version:
        description: go version to use
        required: true
        type: string
        default: "1.19"

      package_path:
        description: package path
        required: true
        type: string
        default: "./..."

      dockerfile_path:
        description: dockerfile path
        required: true
        type: string
        default: "./Dockerfile"

      docker_username:
        description: docker username
        required: true
        type: string
        default: "aerosquirrel"

      image_repository:
        description: image repository
        required: true
        type: string
        default: "aerosquirrel"
      
      image_tag:
        description: image tag
        required: false
        type: string
        default: "latest"

jobs:
  build:
    name: Go Docker Publish
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go ${{ inputs.go_version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go_version }}

    - name: Build
      run: go build -v ${{ inputs.package_path }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build and Push
      run: |
        docker build -t ${{ inputs.docker_username }}/${{ inputs.image_repository }}:${{ inputs.image_tag }} ${{ inputs.dockerfile_path }}
        docker push ${{ inputs.docker_username }}/${{ inputs.image_repository }}:${{ inputs.image_tag }}
